@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant "a:AddStudentCommand" as AddStudentCommand LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
participant "d:DeleteStudentCommand" as DeleteStudentCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("student add n/John Doe")
activate LogicManager

LogicManager -> AddressBookParser : parse("student add n/John Doe")
activate AddressBookParser

create AddStudentCommand
AddressBookParser -> AddStudentCommand
activate AddStudentCommand

AddStudentCommand --> AddressBookParser
deactivate AddStudentCommand

AddressBookParser --> LogicManager : a
deactivate AddressBookParser

LogicManager -> AddStudentCommand : execute()
activate AddStudentCommand

AddStudentCommand -> Model : addPerson
activate Model

Model --> AddStudentCommand
deactivate Model

create DeleteStudentCommand
AddStudentCommand -> DeleteStudentCommand
activate DeleteStudentCommand
DeleteStudentCommand --> AddStudentCommand
deactivate DeleteStudentCommand

AddStudentCommand --> LogicManager : result
deactivate AddStudentCommand
AddStudentCommand -[hidden]-> LogicManager : result
destroy AddStudentCommand

[<--LogicManager
deactivate LogicManager

[-> LogicManager : execute("undo")
activate LogicManager

LogicManager -> AddressBookParser : parse("undo")
activate AddressBookParser

create UndoCommand
AddressBookParser -> UndoCommand
activate UndoCommand

UndoCommand --> AddressBookParser
deactivate UndoCommand

AddressBookParser --> LogicManager : u
deactivate AddressBookParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

LogicManager -> DeleteStudentCommand : execute()
activate DeleteStudentCommand

DeleteStudentCommand -> Model : deletePerson
activate Model

Model --> DeleteStudentCommand
deactivate Model

DeleteStudentCommand --> LogicManager : result
deactivate DeleteStudentCommand
DeleteStudentCommand -[hidden]-> LogicManager : result
destroy DeleteStudentCommand

[<--LogicManager
deactivate LogicManager
@enduml
